version: 4.0.0-D
options:
  debug: true
  hooking:
    leveled-mobs: false
    mcmmo: false
  give-mobs-names: false
  give-all-mobs-names: false
  display-mob-equipment: true
  can-mobs-pick-up-equipment: false
  blank-mob-spawn:
    enabled: false
    skeletons-spawn-without-bow: false
multiworld:
  enabled-worlds:
  - world
drops:
  item-chance: 0.25
  socket-gem-chance: 0.2
  identity-tome-chance: 0.1
  custom-item-chance: 0.1
  unidentified-item-chance: 0.1
components:
  creature-spawning-enabled: true
  repairing-enabled: true
  socketting-enabled: true
  identifying-enabled: true
display:
  item-display-name-format: '%generalprefix% %itemtype%'
  tooltip-format:
  - '&7Type: %mythicmaterial%'
  - '&7Tier:%tiercolor% %tiername%'
  
# VARIBLES TO USE IN ITEM DISPLAY NAME FORMAT
# - %basematerial% : Minecraft's name for the material
# - %mythicmaterial% : Customized name of the material
# - %generalprefix% : A prefix pulled from the general prefix file
# - %generalsuffix% : A suffix pulled from the general suffix file
# - %materialprefix% : A prefix pulled from the material's prefix file (if it has one)
# - %materialsuffix% : A suffix pulled from the material's suffix file (if it has one)
# - %tierprefix% : A prefix pulled from the tier's prefix file (if it has one)
# - %tiersuffix% : A suffix pulled from the tier's suffix file (if it has one)
# - %itemtype% : Customized name of the type of the item (sword, axe, etc.)
# - %materialtype% : Customized name of the material of the item (diamond, wood, etc.)
# - %tiername% : Name of the item's tier
# - %enchantment% : Customized name of the highest enchantment on the item
# - %enchantmentprefix% : A prefix pulled from the highest enchantment's prefix file (if it has one)
# - %enchantmentsuffix% : A suffix pulled from the highest enchantment's suffix file (if it has one)
# 
# VARIABLES TO USE IN FORMAT LORE
# - %itemtype% : Customized name of the type of the item (sword, axe, etc.)
# - %basematerial% : Minecraft's name for the material
# - %mythicmaterial% : Customized name of the material
# - %tiername% : Name of the item's tier
# - %enchantment% : Customized name of the highest enchantment on the item
# - %tiercolor% : display color of the item's tier