main: net.nunnerycode.bukkit.mythicdrops.MythicDrops
name: ${project.build.name}
version: ${project.build.version}
authors: [ToppleTheNun, pur3pow3r]

permissions:
    mythicdrops.command.spawn.wildcard:
        default: op
        description: Allows player to spawn in any tier.
commands:
    mythicdrops:
        description: Base MythicDrops command.
        aliases: [mythicd, mdrops, md]