version: "1.0.0"
options:
  unidentified-chance-to-spawn: 0.5
  identity-tome-chance-to-spawn: 0.1
messages:
  cannot-use: '&6[MythicDrops] &CYou cannot use that Identity Tome on that item! Identifying cancelled!'
  do-not-have: '&6[MythicDrops] &CYou do not have an Identity Tome to use! Identifying cancelled!'
  success: '&6[MythicDrops] &AYou successfully identified your item!'
  instructions: '&6[MythicDrops] &AUse this Identity Tome with an &FUnidentified Item &Ato identify it!'
  commands:
    give-tome-receiver: '&6[MythicDrops] &7You received &F%amount%&7 Identity Tomes.'
    give-tome-sender: '&6[MythicDrops] &F%receiver%&7 has received &F%amount%&7 Identity Tomes.'
    give-unidentified-receiver: '&6[MythicDrops] &7You received &F%amount%&7 Unidentified Items.'
    give-unidentified-sender: '&6[MythicDrops] &F%receiver%&7 has received &F%amount%&7 Unidentified Items.'
items:
  identity-tome:
    name: '&5Identity Tome'
    lore:
    - '&7Right click while equipped'
    - '&7to begin identifying!'
  unidentified:
    name: '&FUnidentified Item'
    lore:
    - '&FRight click an &5Identity Tome'
    - '&Fto begin identifying!'
recipes:
  identity-tome:
    format:
    - '   '
    - ' bb'
    - ' bx'
    keys:
      b: 340;0
      x: 381;0