main: net.nunnerycode.bukkit.mythicdrops.identification.MythicDropsIdentification
name: ${project.build.name}
version: ${project.build.version}
authors: [ToppleTheNun, pur3pow3r]
depend: [MythicDrops]

permissions:
    mythicdrops.ident.command.unidentified:
        default: op
        description: Allows player to use "/mythicdrops spawn" command.
    mythicdrops.ident.command.identitytome:
        default: op
        description: Allows player to use "/mythicdrops tome" command.
    mythicdrops.ident.command.*:
        default: op
        children:
          mythicdrops.ident.command.unidentified: true
          mythicdrops.ident.command.identitytome: true
commands:
    mythicdropsidentification:
      aliases: [mythicdi, mdropsi, mdi]