version: "1.0.0-A"
options:
  use-attacker-item-in-hand: true
  use-attacker-armor-equipped: false
  use-defender-item-in-hand: false
  use-defender-armor-equipped: true
  socket-gem-material-ids:
  - 264
  - 388
  - 399
  socket-gem-chance-to-spawn: 0.25
  item-names-that-cannot-have-sockets:
  - Identity Tome
  - Unidentified Item
language:
  items:
    socketted-item-lore:
    - '&7Find a &6Socket Gem&7 to fill a &6(Socket)&7'
    socketted-item-socket: '&6(Socket)'
    socket-name: '&6Socket Gem - %socketgem%'
    socket-lore:
    - '&7Hold this gem and right-click'
    - '&7to begin socketting!'
    - '&8(&7%type%&8)'
  messages:
    cannot-use: '&6[MythicDrops] &CYou cannot use that Socket Gem on that item! Socketting
      cancelled!'
    do-not-have: '&6[MythicDrops] &CYou do not have a Socket Gem to use! Socketting
      cancelled!'
    success: '&6[MythicDrops] &AYou successfully socketted your item!'
    instructions: '&6[MythicDrops] &AUse this Socket Gem with an item with an empty
      &6(Socket)&A to fill it!'
  command:
    no-access: '&6[MythicDrops] &CYou don''t have access to this command.'
    socket-gem-does-not-exist: '&6[MythicDrops] &CThat Socket Gem does not exist.'
    player-does-not-exist: '&6[MythicDrops] &CThat player does not exist or is not
      online.'
    give-gem-receiver: '&6[MythicDrops] &AYou have recieved &F%amount%&A Socket Gem(s)!'
    give-gem-sender: '&6[MythicDrops] &F%receiver%&A was given &F%amount%&A custom
      Socket Gem(s).'
tier-options:
  common:
    minimum-sockets: 0
    maximum-sockets: 0
  uncommon:
    minimum-sockets: 0
    maximum-sockets: 1
  rare:
    minimum-sockets: 0
    maximum-sockets: 2
  artisan:
    minimum-sockets: 0
    maximum-sockets: 3
  epic:
    minimum-sockets: 0
    maximum-sockets: 4
  exotic:
    minimum-sockets: 0
    maximum-sockets: 5
  legendary:
    minimum-sockets: 0
    maximum-sockets: 6