main: net.nunnerycode.bukkit.mythicdrops.sockets.MythicDropsSockets
name: ${project.build.name}
version: ${project.build.version}
authors: [ToppleTheNun, pur3pow3r]
depend: [MythicDrops]

permissions:
commands:
    mythicdropssockets:
        aliases: [mythicds, mdropss, mds]