main: net.nunnerycode.bukkit.mythicdrops.repair.MythicDropsSockets
name: ${project.build.name}
version: ${project.build.version}
authors: [ToppleTheNun, pur3pow3r]
depend: [MythicDrops]

permissions:
commands: